version: "3.8"
services:
  app:
    build: .
    ports:
      - 8080:80
    environment:
      DB_HOST: db
    volumes:
      - .:/var/www/html/lacommerce
    command: sh -c "php artisan db:create && php artisan migrate && php artisan serve --host 0.0.0.0 --port 80"
    depends_on:
      - db
      - elasticsearch
  db:
    image: mysql:8.0.29
    command: --authentication_policy=mysql_native_password --innodb-use-native-aio=0
    restart: always
    ports:
      - 3307:3306
    volumes:
      - .docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: lacommerce
  elasticsearch:
    image: webhippie/elasticsearch:5.6
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - .docker/volumes/elasticsearch:/var/lib/elasticsearch/data